# -*- coding: utf-8 -*-
"""f_to_c

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ND263rTq_0NKJF99ursN8kzlWWFW4F__
"""

# CS 175
# Christopher Kenny
# Problem 4

#Allow user to enter given temperature
temp = int(input("Enter the temperature in Farenheit you would like converted to Celcius: "))

#Conversion Formula
celcius = (temp - 32) * 5/9

#Output to User
print(f"{temp}°F converted to celcius is {celcius}°C")