# -*- coding: utf-8 -*-
"""format_print

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEfvI_AviU5fCoVyOQ6T0G29vWzEfoRH
"""

#CS 175
#Christopher Kenny
#Problem 5

#Copied from Word Document
num1 = 1.8
num2 = 12.9
num3 = 2
num4 = 100.25

#Modified print statement
print(f"{num1:6.2f}",f"{num2:6.2f}",f"{num3:6.2f}",f"{num4:6.2f}",sep ="\n")