# -*- coding: utf-8 -*-
"""myInfo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYgr9dCHcCsEfGuJaMAy-BEKznkiaDSG
"""

# CS175-50
# Christopher Kenny
#myInfo

print("Hello, my name is Christopher Kenny.")
print("I live at 1 Blueberry Muffin Lane in Brick, New Jersey 08723.")
print("You can contact me at (678) 999-8212.")