# -*- coding: utf-8 -*-
"""name_printer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DqNKqts_3lOjJAt_2R14KC6v1uKIl6Fu
"""

# CS175
# Christopher Kenny
# Problem 1

print("+-------+")
print("| Chris |")
print("+-------+")

