# -*- coding: utf-8 -*-
"""print_grid

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwYCwg_ivrcCjvdGduZX1DSrRcjuG_ZL
"""

#CS 175
#Christopher Kenny
#Problem 6

#Variables
pattern1 = "+--+--+--+ \n|  |  |  |"
pattern2 = "+--+--+--+"

print(pattern1)
print(pattern1)
print(pattern1)
print(pattern2)

